"""Project deployer — install Botte Secrète's token-saving stack into a project.

This is the point of the whole toolkit: take an arbitrary project and wire it up
so its agent spends fewer tokens and less money. One call does:

  1. discover local LLM backends (so routing has somewhere to send work)
  2. register the botte-llm MCP server in the project's .mcp.json
     → the project's agent gains local_chat / auto_route / fusion / find_skills /
       audit tools, all pointing back at this repo
  3. audit the project's agent directives (CLAUDE.md / AGENTS.md / specs)
  4. write .botte/config.json (chosen local model, budget, routing prefs)
  5. write .botte/setup-report.json + print a summary with estimated savings

Idempotent: re-running updates rather than duplicates. Pure stdlib.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# Repo root = where this toolkit lives (skills/bootstrap/setup.py → parents[2]).
BOTTE_ROOT = Path(__file__).resolve().parents[2]

MCP_SERVER_NAME = "botte-llm"


# ── .mcp.json wiring ──────────────────────────────────────────────────────────

def _mcp_server_entry() -> dict:
    return {
        "command": sys.executable or "python",
        "args": ["-m", "skills.llm_mcp.server"],
        "cwd": str(BOTTE_ROOT),
    }


def wire_mcp(project: Path) -> dict:
    """Merge the botte-llm server into the project's .mcp.json (non-destructive)."""
    mcp_path = project / ".mcp.json"
    doc: dict = {}
    if mcp_path.exists():
        try:
            doc = json.loads(mcp_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            doc = {}
    servers = doc.setdefault("mcpServers", {})
    existed = MCP_SERVER_NAME in servers
    servers[MCP_SERVER_NAME] = _mcp_server_entry()
    mcp_path.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"path": str(mcp_path), "action": "updated" if existed else "added",
            "other_servers": [k for k in servers if k != MCP_SERVER_NAME]}


def _oculix_mcp_jar() -> Optional[Path]:
    """Locate the OculiX visual-control MCP server jar, if installed."""
    env = os.environ.get("OCULIX_MCP_JAR")
    if env and Path(env).exists():
        return Path(env)
    cand = Path.home() / ".oculix" / "oculix-mcp-server.jar"
    return cand if cand.exists() else None


def wire_oculix_mcp(project: Path) -> dict:
    """Register the OculiX visual-control MCP server in .mcp.json, if its jar exists.

    Gives the agent screen-vision/click tools (find_image, click_image, …) with an
    Ed25519-signed audit journal — local, 0 cloud vision. Non-destructive.
    """
    jar = _oculix_mcp_jar()
    if not jar:
        return {"action": "skipped", "reason": "OculiX MCP jar not found "
                "(~/.oculix/oculix-mcp-server.jar or $OCULIX_MCP_JAR)"}
    mcp_path = project / ".mcp.json"
    doc: dict = {}
    if mcp_path.exists():
        try:
            doc = json.loads(mcp_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            doc = {}
    servers = doc.setdefault("mcpServers", {})
    existed = "oculix" in servers
    servers["oculix"] = {"command": "java",
                         "args": ["--enable-native-access=ALL-UNNAMED",
                                  "-jar", str(jar), "run"]}
    mcp_path.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"action": "updated" if existed else "added", "jar": str(jar)}


def _hook_entry() -> dict:
    return {"type": "command",
            "command": f'"{sys.executable or "python"}" -m skills.preflight.hook',
            "cwd": str(BOTTE_ROOT)}


def wire_hook(project: Path) -> dict:
    """Add the preflight UserPromptSubmit hook to .claude/settings.json (non-destructive).

    Makes the prefer-local policy + skill suggestions automatic on every prompt,
    instead of relying on the model remembering. Idempotent.
    """
    settings_path = project / ".claude" / "settings.json"
    doc: dict = {}
    if settings_path.exists():
        try:
            doc = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            doc = {}
    hooks = doc.setdefault("hooks", {})
    ups = hooks.setdefault("UserPromptSubmit", [])
    marker = "skills.preflight.hook"
    already = any(marker in json.dumps(group) for group in ups)
    if not already:
        ups.append({"hooks": [_hook_entry()]})
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        settings_path.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"path": str(settings_path), "action": "present" if already else "added"}


# ── starter AGENTS.md ─────────────────────────────────────────────────────────

_STARTER_AGENTS = """# AGENTS.md

Guidance for AI agents working in this project. (Generated by Botte Secrète —
edit freely.)

## Setup & commands
- Build: <fill in>
- Test:  <fill in>
- Lint:  <fill in>

## Conventions
- Prefer the smallest change that works; don't cut validation, error handling,
  security or accessibility.
- Route cheap work (classification, extraction, short summaries) to local models
  via the `botte-llm` MCP tools (auto_route / local_chat) to save cloud tokens.
- Pick tools with `find_skills` before reaching for the cloud model.

## Notes
<project-specific context, intent, decided trade-offs>
"""


def ensure_agents_md(project: Path, create: bool) -> dict:
    """If no instruction file exists and create=True, write a starter AGENTS.md."""
    try:
        from skills.directives_audit import audit as dir_audit
    except ImportError:
        return {"available": False}
    report = dir_audit(project)
    out = {"available": True, "score": report["score"],
           "has_instructions": report["has_instructions"],
           "findings": len(report["findings"])}
    if not report["has_instructions"] and create:
        target = project / "AGENTS.md"
        if not target.exists():
            target.write_text(_STARTER_AGENTS, encoding="utf-8")
            out["created"] = "AGENTS.md"
    return out


# ── per-project config ────────────────────────────────────────────────────────

@dataclass
class BotteConfig:
    botte_root: str
    local_backend: Optional[str]
    local_model: Optional[str]
    cloud_keys_present: list
    daily_token_budget: int = 50000
    routing: str = "auto"   # auto local↔cloud via skills.auto_router

    def to_dict(self) -> dict:
        return self.__dict__


def _detect_cloud_keys() -> list:
    import os
    env = ("OPENROUTER_API_KEY", "DEEPSEEK_API_KEY", "XAI_API_KEY",
           "ZHIPUAI_API_KEY", "NVIDIA_API_KEY")
    return [k for k in env if os.environ.get(k)]


def write_config(project: Path) -> dict:
    from skills.llm_backends import registry
    best = registry.best_chat_backend()
    cfg = BotteConfig(
        botte_root=str(BOTTE_ROOT),
        local_backend=f"{best.host}:{best.port}" if best else None,
        local_model=registry.preferred_model(best) if best else None,
        cloud_keys_present=_detect_cloud_keys(),
    )
    botte_dir = project / ".botte"
    botte_dir.mkdir(exist_ok=True)
    cfg_path = botte_dir / "config.json"
    cfg_path.write_text(json.dumps(cfg.to_dict(), indent=2, ensure_ascii=False),
                        encoding="utf-8")
    return {"path": str(cfg_path), "config": cfg.to_dict()}


# ── orchestration ─────────────────────────────────────────────────────────────

def setup(project: str | Path, *, create_agents_md: bool = False,
          scan_subnet: bool = False) -> dict:
    """Deploy the full stack into `project`. Returns a setup report."""
    project = Path(project).resolve()
    if not project.is_dir():
        raise NotADirectoryError(f"Not a directory: {project}")

    from skills.llm_backends import registry
    backends = registry.refresh(scan_subnet=scan_subnet)
    chat = registry.chat_backends(backends)

    mcp = wire_mcp(project)
    directives = ensure_agents_md(project, create_agents_md)
    config = write_config(project)

    # Enforcement layer: commit the shared policy, wire the preflight hook so the
    # prefer-local rules apply automatically, and point AGENTS.md at the policy.
    from skills.preflight import policy as _policy
    policy_written = _policy.write_default(project)
    pointer_added = _policy.ensure_agents_pointer(project)
    hook = wire_hook(project)
    oculix_mcp = wire_oculix_mcp(project)

    # Quick skill-catalog sizing (what the local finder will search for free).
    try:
        from skills.skill_finder import load_catalog
        catalog_size = len(load_catalog([BOTTE_ROOT / "skills"]))
    except ImportError:
        catalog_size = 0

    report = {
        "project": str(project),
        "botte_root": str(BOTTE_ROOT),
        "local_backends": [f"{b.label} {b.host}:{b.port}" for b in chat],
        "cloud_keys_present": _detect_cloud_keys(),
        "mcp": mcp,
        "directives": directives,
        "config": config["path"],
        "policy": {"written": str(policy_written) if policy_written else "exists",
                   "agents_pointer_added": pointer_added},
        "hook": hook,
        "oculix_mcp": oculix_mcp,
        "skill_catalog_size": catalog_size,
        "next_steps": _next_steps(chat, directives),
    }
    botte_dir = project / ".botte"
    botte_dir.mkdir(exist_ok=True)
    (botte_dir / "setup-report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    return report


def _next_steps(chat, directives: dict) -> list:
    steps = []
    if not chat:
        steps.append("No local LLM detected — run `python -m skills.llm_backends.cli "
                     "audit --fresh` for hardware-aware setup (LM Studio / Ollama).")
    else:
        steps.append("Local routing active — cheap tasks will run on "
                     f"{chat[0].label} for 0 cloud tokens.")
    steps.append("Restart your agent in the project so it picks up .mcp.json "
                 "(tools: auto_route, local_chat, fusion, find_skills, audit_local_usage).")
    if directives.get("available") and not directives.get("has_instructions") \
            and not directives.get("created"):
        steps.append("No CLAUDE.md/AGENTS.md — re-run with --create-agents-md to scaffold one.")
    return steps
