"""app_test — local-first GUI app testing via image matching (SikuliX).

The idea (from the video): when you build a UI you already have the button
images, so an image-matching bot can click them — no cloud vision needed. This
turns a tiny JSON spec into a runnable SikuliX script and runs it locally, using
a vision NPU (Hailo-8/10) or a local vision model only for richer verification.

A spec is JSON:

    {
      "name": "login_flow",
      "image_dir": "tests/images",          # where the button PNGs live
      "similarity": 0.8,                      # match threshold
      "steps": [
        {"do": "wait",   "image": "login_btn.png", "timeout": 10},
        {"do": "click",  "image": "login_btn.png"},
        {"do": "type",   "text": "user@example.com"},
        {"do": "click",  "image": "submit.png"},
        {"do": "assert_visible", "image": "welcome.png", "timeout": 8}
      ]
    }

`to_sikulix_script` is pure/deterministic (unit-tested). `run` shells out to
SikuliX if it's installed; otherwise it reports how to get it. Pure stdlib.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional

_ACTIONS = {"wait", "click", "double_click", "right_click", "type", "assert_visible",
            "assert_absent", "sleep"}


def load_spec(path: str | Path) -> dict:
    spec = json.loads(Path(path).read_text(encoding="utf-8"))
    if "steps" not in spec or not isinstance(spec["steps"], list):
        raise ValueError("spec needs a 'steps' list")
    for i, s in enumerate(spec["steps"]):
        if s.get("do") not in _ACTIONS:
            raise ValueError(f"step {i}: unknown action {s.get('do')!r} "
                             f"(allowed: {', '.join(sorted(_ACTIONS))})")
        if s["do"] in ("wait", "click", "double_click", "right_click",
                       "assert_visible", "assert_absent") and not s.get("image"):
            raise ValueError(f"step {i}: action {s['do']} needs an 'image'")
        if s["do"] == "type" and "text" not in s:
            raise ValueError(f"step {i}: 'type' needs 'text'")
    return spec


def _img(image_dir: str, name: str) -> str:
    p = (Path(image_dir) / name).as_posix() if image_dir else name
    return p.replace('"', '\\"')


def to_sikulix_script(spec: dict, artifacts_dir: Optional[str] = None) -> str:
    """Render a SikuliX/OculiX (Jython) script from the spec. Deterministic.

    If `artifacts_dir` is given, a screenshot is saved after each step (a
    ffmpeg-free "filmstrip" for post-mortem), guarded so it never breaks the run.
    """
    image_dir = spec.get("image_dir", "")
    sim = float(spec.get("similarity", 0.8))
    lines = [
        f"# Auto-generated by botte-secrete app_test — {spec.get('name', 'test')}",
        "import sys",
        f"setAutoWaitTimeout(10)",
        f"Settings.MinSimilarity = {sim}",
        "errors = 0",
    ]
    if artifacts_dir:
        ad = artifacts_dir.replace("\\", "/").replace('"', '\\"')
        lines += [
            "import shutil as _sh",
            "def _shot(i):",
            "    try:",
            f'        _sh.copy(str(capture()), "{ad}/step_%02d.png" % i)',
            "    except Exception:",
            "        pass",
        ]
    for i, s in enumerate(spec["steps"]):
        do = s["do"]
        img = _img(image_dir, s["image"]) if s.get("image") else ""
        to = float(s.get("timeout", 10))
        if do == "wait":
            lines.append(f'try:\n    wait("{img}", {to})\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: wait {img}"); errors += 1')
        elif do == "click":
            lines.append(f'try:\n    click("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: click {img}"); errors += 1')
        elif do == "double_click":
            lines.append(f'try:\n    doubleClick("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: doubleClick {img}"); errors += 1')
        elif do == "right_click":
            lines.append(f'try:\n    rightClick("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: rightClick {img}"); errors += 1')
        elif do == "type":
            text = str(s["text"]).replace('"', '\\"')
            lines.append(f'type("{text}")')
        elif do == "sleep":
            lines.append(f"wait({to})")
        elif do == "assert_visible":
            lines.append(f'if exists("{img}", {to}):\n    print("STEP {i} OK: visible {img}")\n'
                         f'else:\n    print("STEP {i} FAIL: not visible {img}"); errors += 1')
        elif do == "assert_absent":
            lines.append(f'if exists("{img}", {to}):\n    print("STEP {i} FAIL: still visible {img}"); errors += 1\n'
                         f'else:\n    print("STEP {i} OK: absent {img}")')
        if artifacts_dir:
            lines.append(f"_shot({i})")
    lines.append('print("RESULT: %d errors" % errors)')
    lines.append("sys.exit(1 if errors else 0)")
    return "\n".join(lines)


def find_sikulix() -> Optional[str]:
    """Locate a visual-automation runner: OculiX (preferred) or SikuliX.

    Order: OCULIX_JAR / SIKULIX_JAR env → known install jars (~/.oculix,
    ~/.sikulix) → runsikulix/oculix on PATH. OculiX is a drop-in SikuliX fork,
    so the generated `-r <bundle>` scripts run on either.
    """
    for env in ("OCULIX_JAR", "SIKULIX_JAR"):
        jar = os.environ.get(env)
        if jar and Path(jar).exists():
            return jar
    home = Path.home()
    for cand in (home / ".oculix" / "oculixide.jar",
                 home / ".oculix" / "oculix.jar"):
        if cand.exists():
            return str(cand)
    for d in (home / ".sikulix", home / ".oculix"):
        if d.exists():
            for jar in sorted(d.glob("*ide*.jar")) or sorted(d.glob("*.jar")):
                return str(jar)
    for exe in ("oculix", "runsikulix", "sikulix"):
        if shutil.which(exe):
            return exe
    return None


def write_script(spec: dict, out_dir: str | Path) -> Path:
    """Write a .sikuli bundle (dir + script.py + artifacts/) and return the bundle."""
    name = spec.get("name", "test")
    bundle = Path(out_dir) / f"{name}.sikuli"
    bundle.mkdir(parents=True, exist_ok=True)
    artdir = bundle / "artifacts"
    artdir.mkdir(exist_ok=True)
    (bundle / f"{name}.py").write_text(
        to_sikulix_script(spec, artifacts_dir=str(artdir)), encoding="utf-8")
    return bundle


def run(spec_path: str | Path, out_dir: str | Path = ".", *, report: bool = True) -> dict:
    """Generate + (if a runner is present) run the test, capturing dev artifacts.

    Always generates the bundle. When a runner is found, runs it, then collects
    step results, failure/step screenshots and any logs declared in the spec
    (`"logs": [paths]`), and writes a self-contained HTML post-mortem report.
    """
    spec = load_spec(spec_path)
    bundle = write_script(spec, out_dir)
    name = spec.get("name", "test")
    runner = find_sikulix()
    if not runner:
        return {"ran": False, "script": str(bundle),
                "reason": "No runner — install OculiX (github.com/oculix-org/Oculix"
                          "/releases → ~/.oculix/oculixide.jar) or set OCULIX_JAR. "
                          "Java required.",
                "steps": len(spec["steps"])}
    if runner.endswith(".jar"):
        cmd = ["java", "--enable-native-access=ALL-UNNAMED", "-jar", runner,
               "-r", str(bundle), "-c"]
    else:
        cmd = [runner, "-r", str(bundle)]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    except (OSError, subprocess.SubprocessError) as e:
        return {"ran": False, "script": str(bundle), "reason": str(e)}

    out = (proc.stdout or "") + (proc.stderr or "")
    result = {"ran": True, "script": str(bundle), "runner": runner,
              "exit": proc.returncode, "passed": proc.returncode == 0,
              "output": out[-3000:]}
    if report:
        from skills.app_test.artifacts import html_report, collect_logs, parse_steps
        logs = collect_logs(spec.get("logs", []))
        rpt = html_report(name, output=out, steps=parse_steps(out), logs=logs,
                          artifacts_dir=bundle / "artifacts",
                          out_path=Path(out_dir) / f"{name}-report.html")
        result["report"] = str(rpt)
        result["logs_collected"] = list(logs.keys())
    return result
