"""app_test — local-first GUI app testing via image matching (SikuliX).

The idea (from the video): when you build a UI you already have the button
images, so an image-matching bot can click them — no cloud vision needed. This
turns a tiny JSON spec into a runnable SikuliX script and runs it locally, using
a vision NPU (Hailo-8/10) or a local vision model only for richer verification.

A spec is JSON:

    {
      "name": "login_flow",
      "image_dir": "tests/images",          # where the button PNGs live
      "similarity": 0.8,                      # match threshold
      "steps": [
        {"do": "wait",   "image": "login_btn.png", "timeout": 10},
        {"do": "click",  "image": "login_btn.png"},
        {"do": "type",   "text": "user@example.com"},
        {"do": "click",  "image": "submit.png"},
        {"do": "assert_visible", "image": "welcome.png", "timeout": 8}
      ]
    }

`to_sikulix_script` is pure/deterministic (unit-tested). `run` shells out to
SikuliX if it's installed; otherwise it reports how to get it. Pure stdlib.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional

_ACTIONS = {"wait", "click", "double_click", "right_click", "type", "assert_visible",
            "assert_absent", "sleep"}


def load_spec(path: str | Path) -> dict:
    spec = json.loads(Path(path).read_text(encoding="utf-8"))
    if "steps" not in spec or not isinstance(spec["steps"], list):
        raise ValueError("spec needs a 'steps' list")
    for i, s in enumerate(spec["steps"]):
        if s.get("do") not in _ACTIONS:
            raise ValueError(f"step {i}: unknown action {s.get('do')!r} "
                             f"(allowed: {', '.join(sorted(_ACTIONS))})")
        if s["do"] in ("wait", "click", "double_click", "right_click",
                       "assert_visible", "assert_absent") and not s.get("image"):
            raise ValueError(f"step {i}: action {s['do']} needs an 'image'")
        if s["do"] == "type" and "text" not in s:
            raise ValueError(f"step {i}: 'type' needs 'text'")
    return spec


def _img(image_dir: str, name: str) -> str:
    p = (Path(image_dir) / name).as_posix() if image_dir else name
    return p.replace('"', '\\"')


def to_sikulix_script(spec: dict) -> str:
    """Render a SikuliX (Jython) script from the spec. Deterministic."""
    image_dir = spec.get("image_dir", "")
    sim = float(spec.get("similarity", 0.8))
    lines = [
        f"# Auto-generated by botte-secrete app_test — {spec.get('name', 'test')}",
        "import sys",
        f"setAutoWaitTimeout(10)",
        f"Settings.MinSimilarity = {sim}",
        "errors = 0",
    ]
    for i, s in enumerate(spec["steps"]):
        do = s["do"]
        img = _img(image_dir, s["image"]) if s.get("image") else ""
        to = float(s.get("timeout", 10))
        if do == "wait":
            lines.append(f'try:\n    wait("{img}", {to})\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: wait {img}"); errors += 1')
        elif do == "click":
            lines.append(f'try:\n    click("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: click {img}"); errors += 1')
        elif do == "double_click":
            lines.append(f'try:\n    doubleClick("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: doubleClick {img}"); errors += 1')
        elif do == "right_click":
            lines.append(f'try:\n    rightClick("{img}")\nexcept FindFailed:\n'
                         f'    print("STEP {i} FAIL: rightClick {img}"); errors += 1')
        elif do == "type":
            text = str(s["text"]).replace('"', '\\"')
            lines.append(f'type("{text}")')
        elif do == "sleep":
            lines.append(f"wait({to})")
        elif do == "assert_visible":
            lines.append(f'if exists("{img}", {to}):\n    print("STEP {i} OK: visible {img}")\n'
                         f'else:\n    print("STEP {i} FAIL: not visible {img}"); errors += 1')
        elif do == "assert_absent":
            lines.append(f'if exists("{img}", {to}):\n    print("STEP {i} FAIL: still visible {img}"); errors += 1\n'
                         f'else:\n    print("STEP {i} OK: absent {img}")')
    lines.append('print("RESULT: %d errors" % errors)')
    lines.append("sys.exit(1 if errors else 0)")
    return "\n".join(lines)


def find_sikulix() -> Optional[str]:
    """Locate a SikuliX runner (env SIKULIX_JAR, or runsikulix on PATH)."""
    jar = os.environ.get("SIKULIX_JAR")
    if jar and Path(jar).exists():
        return jar
    for exe in ("runsikulix", "sikulix"):
        if shutil.which(exe):
            return exe
    return None


def write_script(spec: dict, out_dir: str | Path) -> Path:
    """Write a .sikuli bundle (dir + script.py) and return the bundle path."""
    name = spec.get("name", "test")
    bundle = Path(out_dir) / f"{name}.sikuli"
    bundle.mkdir(parents=True, exist_ok=True)
    (bundle / f"{name}.py").write_text(to_sikulix_script(spec), encoding="utf-8")
    return bundle


def run(spec_path: str | Path, out_dir: str | Path = ".") -> dict:
    """Generate + (if SikuliX is present) run the test. Always generates the script."""
    spec = load_spec(spec_path)
    bundle = write_script(spec, out_dir)
    runner = find_sikulix()
    if not runner:
        return {"ran": False, "script": str(bundle),
                "reason": "SikuliX not found — set SIKULIX_JAR or install runsikulix "
                          "(https://github.com/RaiMan/SikuliX1). Java is required.",
                "steps": len(spec["steps"])}
    cmd = ([runner, "-r", str(bundle)] if runner.endswith(("runsikulix", "sikulix"))
           else ["java", "-jar", runner, "-r", str(bundle)])
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        return {"ran": True, "script": str(bundle), "exit": proc.returncode,
                "passed": proc.returncode == 0,
                "output": (proc.stdout or "")[-2000:]}
    except (OSError, subprocess.SubprocessError) as e:
        return {"ran": False, "script": str(bundle), "reason": str(e)}
